# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ${registry}/rayproject/ray:2.48.0.2c63f6-py312-cu128

# additional binaries for rdma
RUN sudo apt update -y \
    && sudo apt upgrade -y \
    && sudo apt install libnl-3-200 libnl-route-3-200 -y \
    && sudo apt autoremove -y \
    && sudo apt clean

# The keyring is needed to access Artifact Registry
# See: https://cloud.google.com/artifact-registry/docs/python/authentication
RUN pip install --no-cache-dir keyring \
    && pip install --no-cache-dir keyrings.google-artifactregistry-auth
