steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#   - 'build'
#   - '--network=cloudbuild'
#   - '-t'
#   - '${_REPO}/ray-cluster'
#   - '.'

# - name: 'gcr.io/cloud-builders/docker'
#   args:
#   - 'push'
#   - '${_REPO}/ray-cluster'

# See: https://cloud.google.com/artifact-analysis/docs/generate-store-sboms
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'artifacts'
  - 'sbom'
  - 'export'
  - '--uri'
  - '${_REPO}/ray-cluster'

options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  requestedVerifyOption: VERIFIED

substitutions:
  _REPO: $LOCATION-docker.pkg.dev/$PROJECT_ID/oasis


images: ['${_REPO}/ray-cluster']
